version: "3.8"

services:
  backend:
    build: .
    expose: ["5000"]
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data      # TLS certs
      - caddy_config:/config
    depends_on: [backend]
    restart: always

volumes:
  caddy_data:
  caddy_config:
